-- 도감 마스터 — 사람이 정한 200종 (id 1~200)
--
-- **생성물이다. 직접 고치지 않는다.** 원본은 `공용_적재/seed_flowers_sql.py`이고
-- 그 입력은 `공용_적재/flowers.json`(← `꽃도감/꽃목록_200종.csv`)이다.
-- 꽃 데이터를 바꾸려면 `꽃도감/_tools/flowers.py`부터 고친다.
--
-- `bloom_months`는 **이미 파싱된 값**이다 (공유계약 1-2: 파싱은 단 한 번).
-- 적용: 0001_init.sql 다음에 SQL Editor에서 Run. 여러 번 돌려도 안전하다.
--
-- ⚠️ **여기에 신규 1,857종은 없다.** 그건 `0006_seed_flowers_2057.sql`이고,
--    0001의 제약(`id between 1 and 200` · `season not null` 등) 때문에
--    **0005가 먼저 돌아야** 들어간다. 파일이 두 개인 이유가 그것이다.
-- ⚠️ **`bloom_source` 컬럼을 여기서 적지 않는다.** 이 파일은 그 컬럼이 생기기 전
--    스키마에서도 돌아야 한다(합본은 번호순이다). 0005가 기본값 `'human'`을 주고,
--    id 1~200은 실제로 사람이 정한 값이라 그 기본값이 사실과 맞다.

insert into public.flowers
  (id, name, scientific_name, family, bloom_months, bloom_label, season, color, rarity, habitat, ai_difficulty, similar_flower_ids, illust_batch)
values
  (1, '개나리', 'Forsythia koreana', '물푸레나무과', '{3,4}', '3~4월', 'spring', '노랑', 'common', '담장·공원 울타리', 'low', '{13}', 1),
  (2, '진달래', 'Rhododendron mucronulatum', '진달래과', '{3,4}', '3~4월', 'spring', '분홍', 'common', '산지·공원 사면', 'mid', '{3,4}', 1),
  (3, '철쭉', 'Rhododendron schlippenbachii', '진달래과', '{4,5}', '4~5월', 'spring', '분홍', 'common', '산지·공원', 'mid', '{2,4}', 1),
  (4, '영산홍', 'Rhododendron indicum', '진달래과', '{4,5}', '4~5월', 'spring', '붉은색', 'common', '화단·가로 조경', 'mid', '{3,2}', 1),
  (5, '벚꽃', 'Prunus × yedoensis', '장미과', '{4}', '4월', 'spring', '분홍', 'common', '가로수·공원', 'high', '{6,7,9}', 1),
  (6, '매화', 'Prunus mume', '장미과', '{2,3,4}', '2~4월', 'winter', '흰색', 'normal', '공원·정원', 'high', '{5,7}', 1),
  (7, '살구꽃', 'Prunus armeniaca', '장미과', '{4}', '4월', 'spring', '분홍', 'normal', '주택가·농가', 'high', '{6,5,8}', 2),
  (8, '복사꽃', 'Prunus persica', '장미과', '{4,5}', '4~5월', 'spring', '분홍', 'normal', '과수원·주택가', 'high', '{7,5}', 2),
  (9, '자두꽃', 'Prunus salicina', '장미과', '{4}', '4월', 'spring', '흰색', 'normal', '과수원·주택가', 'high', '{6,5}', 3),
  (10, '백목련', 'Magnolia denudata', '목련과', '{3,4}', '3~4월', 'spring', '흰색', 'common', '공원·학교', 'mid', '{11,12}', 1),
  (11, '목련', 'Magnolia kobus', '목련과', '{3,4}', '3~4월', 'spring', '흰색', 'normal', '공원·산지', 'mid', '{10}', 2),
  (12, '자목련', 'Magnolia liliiflora', '목련과', '{4,5}', '4~5월', 'spring', '보라', 'normal', '공원·정원', 'low', '{10}', 2),
  (13, '산수유', 'Cornus officinalis', '층층나무과', '{3,4}', '3~4월', 'spring', '노랑', 'common', '공원·가로수', 'mid', '{1,14}', 1),
  (14, '생강나무', 'Lindera obtusiloba', '녹나무과', '{3}', '3월', 'spring', '노랑', 'normal', '산지 등산로', 'high', '{13}', 3),
  (15, '동백꽃', 'Camellia japonica', '차나무과', '{12,1,2,3,4}', '12~4월', 'winter', '붉은색', 'normal', '남부 해안·공원', 'low', '{16}', 1),
  (16, '애기동백', 'Camellia sasanqua', '차나무과', '{10,11,12}', '10~12월', 'winter', '분홍', 'normal', '공원·정원', 'mid', '{15}', 2),
  (17, '명자나무꽃', 'Chaenomeles speciosa', '장미과', '{4,5}', '4~5월', 'spring', '붉은색', 'normal', '정원·울타리', 'mid', '{15}', 2),
  (18, '조팝나무', 'Spiraea prunifolia', '장미과', '{4}', '4월', 'spring', '흰색', 'common', '공원·도로변', 'mid', '{26}', 1),
  (19, '수수꽃다리', 'Syringa dilatata', '물푸레나무과', '{4,5}', '4~5월', 'spring', '보라', 'common', '공원·학교', 'mid', '{}', 1),
  (20, '이팝나무', 'Chionanthus retusus', '물푸레나무과', '{5,6}', '5~6월', 'spring', '흰색', 'common', '가로수', 'mid', '{26}', 2),
  (21, '아까시나무', 'Robinia pseudoacacia', '콩과', '{5,6}', '5~6월', 'spring', '흰색', 'common', '산지·도로변', 'mid', '{91}', 1),
  (22, '등나무', 'Wisteria floribunda', '콩과', '{5}', '5월', 'spring', '보라', 'common', '공원 그늘막·정자', 'low', '{93}', 1),
  (23, '병꽃나무', 'Weigela subsessilis', '인동과', '{5}', '5월', 'spring', '붉은색', 'normal', '산지·공원', 'mid', '{}', 3),
  (24, '황매화', 'Kerria japonica', '장미과', '{4,5}', '4~5월', 'spring', '노랑', 'normal', '공원·화단', 'mid', '{}', 2),
  (25, '산딸나무', 'Cornus kousa', '층층나무과', '{5,6}', '5~6월', 'spring', '흰색', 'normal', '공원·가로수', 'low', '{}', 2),
  (26, '쥐똥나무', 'Ligustrum obtusifolium', '물푸레나무과', '{5,6}', '5~6월', 'spring', '흰색', 'common', '울타리·도로변', 'mid', '{20,18}', 2),
  (27, '모란', 'Paeonia suffruticosa', '작약과', '{5}', '5월', 'spring', '붉은색', 'normal', '정원·고궁', 'mid', '{28}', 2),
  (28, '작약', 'Paeonia lactiflora', '작약과', '{5,6}', '5~6월', 'spring', '분홍', 'normal', '화단·농가', 'mid', '{27}', 2),
  (29, '찔레꽃', 'Rosa multiflora', '장미과', '{5,6}', '5~6월', 'spring', '흰색', 'common', '들·산기슭', 'mid', '{81,82}', 1),
  (30, '마가목', 'Sorbus commixta', '장미과', '{5,6}', '5~6월', 'spring', '흰색', 'normal', '공원·산지', 'high', '{}', 3),
  (31, '민들레', 'Taraxacum platycarpum', '국화과', '{3,4,5}', '3~5월', 'spring', '노랑', 'common', '길가·공터', 'mid', '{32,45}', 1),
  (32, '서양민들레', 'Taraxacum officinale', '국화과', '{3,4,5,6,7,8,9,10}', '3~10월', 'spring', '노랑', 'common', '길가·공터', 'high', '{31}', 1),
  (33, '제비꽃', 'Viola mandshurica', '제비꽃과', '{4,5}', '4~5월', 'spring', '보라', 'common', '길가·잔디밭', 'mid', '{34,73}', 1),
  (34, '남산제비꽃', 'Viola albida', '제비꽃과', '{4,5}', '4~5월', 'spring', '흰색', 'normal', '산지', 'high', '{33}', 3),
  (35, '꽃마리', 'Trigonotis peduncularis', '지치과', '{4,5}', '4~5월', 'spring', '파랑', 'common', '길가·잔디밭', 'high', '{36}', 2),
  (36, '큰개불알풀', 'Veronica persica', '현삼과', '{3,4,5}', '3~5월', 'spring', '파랑', 'common', '길가·밭', 'mid', '{35}', 1),
  (37, '봄맞이꽃', 'Androsace umbellata', '앵초과', '{4,5}', '4~5월', 'spring', '흰색', 'normal', '길가·논둑', 'high', '{38}', 3),
  (38, '별꽃', 'Stellaria media', '석죽과', '{3,4,5}', '3~5월', 'spring', '흰색', 'common', '길가·밭', 'high', '{39,40}', 2),
  (39, '쇠별꽃', 'Stellaria aquatica', '석죽과', '{4,5,6}', '4~6월', 'spring', '흰색', 'common', '습한 길가', 'high', '{38}', 3),
  (40, '개별꽃', 'Pseudostellaria heterophylla', '석죽과', '{4,5}', '4~5월', 'spring', '흰색', 'normal', '산지 숲', 'high', '{38}', 3),
  (41, '광대나물', 'Lamium amplexicaule', '꿀풀과', '{3,4,5}', '3~5월', 'spring', '분홍', 'common', '길가·밭', 'mid', '{42}', 2),
  (42, '자주광대나물', 'Lamium purpureum', '꿀풀과', '{3,4,5}', '3~5월', 'spring', '보라', 'normal', '길가·공터', 'high', '{41}', 3),
  (43, '냉이', 'Capsella bursa-pastoris', '십자화과', '{3,4,5}', '3~5월', 'spring', '흰색', 'common', '길가·밭', 'mid', '{}', 2),
  (44, '애기똥풀', 'Chelidonium majus', '양귀비과', '{5,6,7,8}', '5~8월', 'spring', '노랑', 'common', '길가·담장 밑', 'mid', '{45}', 1),
  (45, '씀바귀', 'Ixeris dentata', '국화과', '{5,6,7}', '5~7월', 'spring', '노랑', 'common', '길가·들', 'high', '{46,31}', 2),
  (46, '고들빼기', 'Crepidiastrum sonchifolium', '국화과', '{5,6,7,8}', '5~8월', 'spring', '노랑', 'common', '길가·공터', 'high', '{45,47}', 2),
  (47, '뽀리뱅이', 'Youngia japonica', '국화과', '{5,6}', '5~6월', 'spring', '노랑', 'common', '길가·화단 틈', 'high', '{46}', 3),
  (48, '지칭개', 'Hemistepta lyrata', '국화과', '{5,6,7}', '5~7월', 'spring', '보라', 'common', '길가·공터', 'mid', '{49}', 2),
  (49, '엉겅퀴', 'Cirsium japonicum', '국화과', '{6,7,8}', '6~8월', 'autumn', '보라', 'normal', '들·산기슭', 'mid', '{48}', 2),
  (50, '유채꽃', 'Brassica napus', '십자화과', '{3,4,5}', '3~5월', 'spring', '노랑', 'common', '강변·경관 밭', 'mid', '{}', 1),
  (51, '토끼풀', 'Trifolium repens', '콩과', '{5,6,7,8}', '5~8월', 'spring', '흰색', 'common', '잔디밭·공원', 'low', '{52}', 1),
  (52, '붉은토끼풀', 'Trifolium pratense', '콩과', '{5,6,7,8}', '5~8월', 'spring', '분홍', 'common', '길가·잔디밭', 'low', '{51}', 2),
  (53, '살갈퀴', 'Vicia angustifolia', '콩과', '{4,5}', '4~5월', 'spring', '보라', 'common', '길가·논둑', 'high', '{}', 3),
  (54, '자운영', 'Astragalus sinicus', '콩과', '{4,5}', '4~5월', 'spring', '분홍', 'normal', '논·밭 (남부)', 'mid', '{52}', 3),
  (55, '벌노랑이', 'Lotus corniculatus', '콩과', '{5,6,7,8}', '5~8월', 'spring', '노랑', 'normal', '길가·잔디밭', 'mid', '{}', 3),
  (56, '금낭화', 'Lamprocapnos spectabilis', '현호색과', '{5,6}', '5~6월', 'spring', '분홍', 'normal', '화단·산지', 'low', '{}', 2),
  (57, '현호색', 'Corydalis remota', '현호색과', '{4,5}', '4~5월', 'spring', '보라', 'normal', '산지 숲', 'high', '{}', 3),
  (58, '할미꽃', 'Pulsatilla koreana', '미나리아재비과', '{4,5}', '4~5월', 'spring', '보라', 'rare', '산소·풀밭', 'low', '{}', 3),
  (59, '노루귀', 'Hepatica asiatica', '미나리아재비과', '{3,4}', '3~4월', 'winter', '분홍', 'rare', '산지 숲', 'mid', '{}', 3),
  (60, '복수초', 'Adonis amurensis', '미나리아재비과', '{2,3,4}', '2~4월', 'winter', '노랑', 'rare', '산지 숲', 'mid', '{}', 3),
  (61, '변산바람꽃', 'Eranthis byunsanensis', '미나리아재비과', '{2,3}', '2~3월', 'winter', '흰색', 'rare', '남부 산지', 'mid', '{}', 3),
  (62, '앵초', 'Primula sieboldii', '앵초과', '{4,5}', '4~5월', 'spring', '분홍', 'rare', '산지 습지', 'mid', '{}', 3),
  (63, '은방울꽃', 'Convallaria keiskei', '백합과', '{5,6}', '5~6월', 'spring', '흰색', 'rare', '산지 숲', 'low', '{}', 3),
  (64, '붓꽃', 'Iris sanguinea', '붓꽃과', '{5,6}', '5~6월', 'spring', '보라', 'normal', '공원·화단', 'mid', '{65,66}', 2),
  (65, '꽃창포', 'Iris ensata', '붓꽃과', '{6,7}', '6~7월', 'summer', '보라', 'normal', '물가·습지', 'high', '{64}', 2),
  (66, '노랑꽃창포', 'Iris pseudacorus', '붓꽃과', '{5,6}', '5~6월', 'spring', '노랑', 'normal', '물가·수변공원', 'mid', '{65}', 2),
  (67, '등심붓꽃', 'Sisyrinchium rosulatum', '붓꽃과', '{5,6}', '5~6월', 'spring', '보라', 'normal', '잔디밭 (남부)', 'high', '{}', 3),
  (68, '튤립', 'Tulipa gesneriana', '백합과', '{4,5}', '4~5월', 'spring', '기타', 'common', '화단·공원', 'low', '{}', 1),
  (69, '수선화', 'Narcissus tazetta', '수선화과', '{3,4}', '3~4월', 'spring', '노랑', 'common', '화단·공원', 'low', '{}', 1),
  (70, '히아신스', 'Hyacinthus orientalis', '아스파라거스과', '{4}', '4월', 'spring', '보라', 'normal', '화단·화분', 'low', '{71}', 2),
  (71, '무스카리', 'Muscari armeniacum', '아스파라거스과', '{4,5}', '4~5월', 'spring', '파랑', 'normal', '화단', 'low', '{70}', 2),
  (72, '크로커스', 'Crocus vernus', '붓꽃과', '{3,4}', '3~4월', 'spring', '보라', 'normal', '화단', 'mid', '{}', 3),
  (73, '팬지', 'Viola × wittrockiana', '제비꽃과', '{3,4,5}', '3~5월', 'spring', '기타', 'common', '화단·화분', 'mid', '{74,33}', 1),
  (74, '비올라', 'Viola cornuta', '제비꽃과', '{3,4,5}', '3~5월', 'spring', '기타', 'common', '화단·화분', 'high', '{73}', 2),
  (75, '데이지', 'Bellis perennis', '국화과', '{4,5}', '4~5월', 'spring', '흰색', 'common', '화단', 'mid', '{}', 2),
  (76, '프리지어', 'Freesia refracta', '붓꽃과', '{3,4}', '3~4월', 'spring', '노랑', 'normal', '화단·화분', 'mid', '{}', 3),
  (77, '라넌큘러스', 'Ranunculus asiaticus', '미나리아재비과', '{4,5}', '4~5월', 'spring', '기타', 'normal', '화단·화분', 'mid', '{}', 3),
  (78, '아네모네', 'Anemone coronaria', '미나리아재비과', '{4,5}', '4~5월', 'spring', '기타', 'normal', '화단', 'mid', '{}', 3),
  (79, '꽃잔디', 'Phlox subulata', '꽃고비과', '{4,5}', '4~5월', 'spring', '분홍', 'common', '화단·경사면', 'low', '{}', 1),
  (80, '물망초', 'Myosotis scorpioides', '지치과', '{5,6}', '5~6월', 'spring', '파랑', 'normal', '화단·물가', 'high', '{35}', 3),
  (81, '장미', 'Rosa hybrida', '장미과', '{5,6,7,8,9,10}', '5~10월', 'summer', '붉은색', 'common', '화단·담장', 'mid', '{29,82}', 1),
  (82, '해당화', 'Rosa rugosa', '장미과', '{5,6,7}', '5~7월', 'summer', '분홍', 'normal', '해안·공원', 'mid', '{81,29}', 2),
  (83, '수국', 'Hydrangea macrophylla', '수국과', '{6,7}', '6~7월', 'summer', '파랑', 'common', '공원·정원', 'low', '{84,85}', 1),
  (84, '산수국', 'Hydrangea serrata', '수국과', '{6,7,8}', '6~8월', 'summer', '파랑', 'normal', '산지 계곡', 'mid', '{83}', 2),
  (85, '나무수국', 'Hydrangea paniculata', '수국과', '{7,8,9}', '7~9월', 'summer', '흰색', 'normal', '공원·정원', 'mid', '{83}', 2),
  (86, '능소화', 'Campsis grandiflora', '능소화과', '{7,8}', '7~8월', 'summer', '주황', 'common', '담장·아파트 화단', 'low', '{}', 1),
  (87, '배롱나무', 'Lagerstroemia indica', '부처꽃과', '{7,8,9}', '7~9월', 'summer', '분홍', 'common', '공원·가로수', 'mid', '{}', 1),
  (88, '무궁화', 'Hibiscus syriacus', '아욱과', '{7,8,9}', '7~9월', 'summer', '분홍', 'common', '공원·학교·관공서', 'mid', '{89,117}', 1),
  (89, '부용', 'Hibiscus mutabilis', '아욱과', '{8,9,10}', '8~10월', 'autumn', '분홍', 'normal', '공원·정원', 'high', '{88,117}', 2),
  (90, '자귀나무', 'Albizia julibrissin', '콩과', '{6,7}', '6~7월', 'summer', '분홍', 'common', '공원·도로변', 'low', '{}', 1),
  (91, '회화나무', 'Styphnolobium japonicum', '콩과', '{7,8}', '7~8월', 'summer', '흰색', 'normal', '가로수·고궁', 'high', '{21}', 3),
  (92, '싸리', 'Lespedeza bicolor', '콩과', '{7,8}', '7~8월', 'summer', '보라', 'common', '산기슭·도로 사면', 'mid', '{93}', 2),
  (93, '칡꽃', 'Pueraria lobata', '콩과', '{7,8}', '7~8월', 'summer', '보라', 'common', '산기슭·공터', 'mid', '{92,22}', 2),
  (94, '인동덩굴', 'Lonicera japonica', '인동과', '{5,6,7}', '5~7월', 'summer', '흰색', 'common', '울타리·산기슭', 'mid', '{}', 2),
  (95, '치자나무', 'Gardenia jasminoides', '꼭두서니과', '{6,7}', '6~7월', 'summer', '흰색', 'normal', '정원 (남부)', 'mid', '{}', 3),
  (96, '모감주나무', 'Koelreuteria paniculata', '무환자나무과', '{6,7}', '6~7월', 'summer', '노랑', 'normal', '공원·해안', 'mid', '{}', 3),
  (97, '개오동', 'Catalpa ovata', '능소화과', '{6,7}', '6~7월', 'summer', '흰색', 'normal', '공원·학교', 'mid', '{}', 3),
  (98, '큰꽃으아리', 'Clematis patens', '미나리아재비과', '{5,6}', '5~6월', 'summer', '흰색', 'normal', '화단·울타리', 'mid', '{100}', 2),
  (99, '사위질빵', 'Clematis apiifolia', '미나리아재비과', '{7,8}', '7~8월', 'summer', '흰색', 'common', '산기슭·울타리', 'high', '{100}', 3),
  (100, '으아리', 'Clematis terniflora', '미나리아재비과', '{7,8}', '7~8월', 'summer', '흰색', 'normal', '산기슭', 'high', '{99}', 3),
  (101, '개망초', 'Erigeron annuus', '국화과', '{6,7,8}', '6~8월', 'summer', '흰색', 'common', '공터·길가', 'mid', '{102,103}', 1),
  (102, '망초', 'Conyza canadensis', '국화과', '{7,8,9}', '7~9월', 'summer', '흰색', 'common', '공터·길가', 'high', '{101}', 2),
  (103, '실망초', 'Conyza bonariensis', '국화과', '{7,8,9}', '7~9월', 'summer', '흰색', 'normal', '공터', 'high', '{102}', 3),
  (104, '큰금계국', 'Coreopsis lanceolata', '국화과', '{6,7,8}', '6~8월', 'summer', '노랑', 'common', '도로변·하천', 'mid', '{105,106}', 1),
  (105, '금계국', 'Coreopsis basalis', '국화과', '{6,7,8}', '6~8월', 'summer', '노랑', 'normal', '화단·도로변', 'high', '{104}', 1),
  (106, '기생초', 'Coreopsis tinctoria', '국화과', '{7,8,9}', '7~9월', 'summer', '노랑', 'normal', '도로변·화단', 'mid', '{105}', 2),
  (107, '원추천인국', 'Rudbeckia hirta', '국화과', '{7,8,9}', '7~9월', 'summer', '노랑', 'common', '화단·도로변', 'mid', '{108,109}', 1),
  (108, '삼잎국화', 'Rudbeckia laciniata', '국화과', '{7,8,9}', '7~9월', 'summer', '노랑', 'normal', '하천변·공터', 'mid', '{107}', 2),
  (109, '해바라기', 'Helianthus annuus', '국화과', '{7,8,9}', '7~9월', 'summer', '노랑', 'common', '밭·경관 화단', 'low', '{}', 1),
  (110, '코스모스', 'Cosmos bipinnatus', '국화과', '{8,9,10}', '8~10월', 'autumn', '분홍', 'common', '하천변·길가', 'low', '{111}', 1),
  (111, '노랑코스모스', 'Cosmos sulphureus', '국화과', '{7,8,9,10}', '7~10월', 'summer', '주황', 'common', '도로변·하천', 'mid', '{110,105}', 1),
  (112, '나팔꽃', 'Ipomoea nil', '메꽃과', '{7,8,9}', '7~9월', 'summer', '보라', 'common', '담장·울타리', 'mid', '{113,114}', 1),
  (113, '메꽃', 'Calystegia pubescens', '메꽃과', '{6,7,8}', '6~8월', 'summer', '분홍', 'common', '길가·논둑', 'mid', '{112}', 2),
  (114, '애기나팔꽃', 'Ipomoea lacunosa', '메꽃과', '{7,8,9}', '7~9월', 'summer', '흰색', 'normal', '공터·하천', 'high', '{112}', 3),
  (115, '달맞이꽃', 'Oenothera biennis', '바늘꽃과', '{6,7,8,9}', '6~9월', 'summer', '노랑', 'common', '하천변·공터', 'mid', '{116}', 1),
  (116, '낮달맞이꽃', 'Oenothera speciosa', '바늘꽃과', '{5,6,7,8,9}', '5~9월', 'summer', '분홍', 'common', '화단·도로변', 'low', '{115}', 1),
  (117, '접시꽃', 'Alcea rosea', '아욱과', '{6,7,8}', '6~8월', 'summer', '분홍', 'normal', '화단·담장 밑', 'mid', '{88,89}', 1),
  (118, '패랭이꽃', 'Dianthus chinensis', '석죽과', '{6,7,8}', '6~8월', 'summer', '분홍', 'normal', '화단·길가', 'mid', '{119,120}', 2),
  (119, '수염패랭이꽃', 'Dianthus barbatus', '석죽과', '{6,7}', '6~7월', 'summer', '붉은색', 'normal', '화단', 'mid', '{118}', 3),
  (120, '술패랭이꽃', 'Dianthus longicalyx', '석죽과', '{7,8}', '7~8월', 'summer', '분홍', 'rare', '산지·풀밭', 'mid', '{118}', 3),
  (121, '끈끈이대나물', 'Silene armeria', '석죽과', '{6,7,8}', '6~8월', 'summer', '분홍', 'normal', '길가·공터', 'mid', '{}', 3),
  (122, '꿀풀', 'Prunella vulgaris', '꿀풀과', '{5,6,7}', '5~7월', 'summer', '보라', 'common', '풀밭·산기슭', 'mid', '{123}', 2),
  (123, '배초향', 'Agastache rugosa', '꿀풀과', '{7,8,9}', '7~9월', 'autumn', '보라', 'normal', '산기슭·밭', 'mid', '{122,125}', 2),
  (124, '익모초', 'Leonurus japonicus', '꿀풀과', '{7,8}', '7~8월', 'summer', '분홍', 'normal', '길가·공터', 'high', '{}', 3),
  (125, '층층이꽃', 'Clinopodium chinense', '꿀풀과', '{7,8}', '7~8월', 'summer', '분홍', 'normal', '산기슭·풀밭', 'high', '{123}', 3),
  (126, '박하', 'Mentha canadensis', '꿀풀과', '{7,8,9}', '7~9월', 'summer', '보라', 'normal', '물가·밭', 'high', '{}', 3),
  (127, '라벤더', 'Lavandula angustifolia', '꿀풀과', '{6,7}', '6~7월', 'summer', '보라', 'normal', '화단·허브 농원', 'low', '{}', 2),
  (128, '부처꽃', 'Lythrum anceps', '부처꽃과', '{7,8}', '7~8월', 'summer', '보라', 'normal', '습지·물가', 'mid', '{}', 3),
  (129, '물봉선', 'Impatiens textori', '봉선화과', '{8,9}', '8~9월', 'autumn', '분홍', 'normal', '산지 계곡', 'mid', '{130}', 2),
  (130, '봉선화', 'Impatiens balsamina', '봉선화과', '{7,8,9}', '7~9월', 'summer', '분홍', 'normal', '화단·주택가', 'mid', '{129,166}', 2),
  (131, '노루오줌', 'Astilbe rubra', '범의귀과', '{7,8}', '7~8월', 'summer', '분홍', 'normal', '산지 계곡', 'mid', '{}', 3),
  (132, '돌나물', 'Sedum sarmentosum', '돌나물과', '{5,6}', '5~6월', 'summer', '노랑', 'common', '담장·바위 틈', 'mid', '{133}', 2),
  (133, '기린초', 'Phedimus kamtschaticus', '돌나물과', '{6,7}', '6~7월', 'summer', '노랑', 'normal', '바위·화단', 'mid', '{132}', 3),
  (134, '큰까치수염', 'Lysimachia clethroides', '앵초과', '{6,7,8}', '6~8월', 'summer', '흰색', 'normal', '산기슭·풀밭', 'mid', '{135}', 2),
  (135, '까치수염', 'Lysimachia barystachys', '앵초과', '{6,7,8}', '6~8월', 'summer', '흰색', 'normal', '풀밭', 'high', '{134}', 3),
  (136, '좁쌀풀', 'Lysimachia vulgaris', '앵초과', '{6,7,8}', '6~8월', 'summer', '노랑', 'normal', '습지·풀밭', 'mid', '{}', 3),
  (137, '짚신나물', 'Agrimonia pilosa', '장미과', '{6,7,8}', '6~8월', 'summer', '노랑', 'normal', '산기슭·길가', 'high', '{}', 3),
  (138, '이질풀', 'Geranium thunbergii', '쥐손이풀과', '{8,9}', '8~9월', 'autumn', '분홍', 'normal', '산기슭·길가', 'mid', '{}', 3),
  (139, '여뀌', 'Persicaria hydropiper', '마디풀과', '{6,7,8,9}', '6~9월', 'summer', '분홍', 'common', '물가·논둑', 'high', '{140,141}', 2),
  (140, '개여뀌', 'Persicaria longiseta', '마디풀과', '{6,7,8,9}', '6~9월', 'summer', '분홍', 'common', '길가·물가', 'high', '{139}', 2),
  (141, '고마리', 'Persicaria thunbergii', '마디풀과', '{8,9}', '8~9월', 'autumn', '분홍', 'common', '물가·논둑', 'mid', '{139}', 2),
  (142, '이삭여뀌', 'Persicaria filiformis', '마디풀과', '{7,8}', '7~8월', 'summer', '붉은색', 'normal', '산지 숲', 'high', '{139}', 3),
  (143, '도라지', 'Platycodon grandiflorus', '초롱꽃과', '{7,8}', '7~8월', 'summer', '보라', 'normal', '밭·화단', 'low', '{}', 1),
  (144, '초롱꽃', 'Campanula punctata', '초롱꽃과', '{6,7}', '6~7월', 'summer', '흰색', 'normal', '산기슭·화단', 'mid', '{145}', 2),
  (145, '섬초롱꽃', 'Campanula takesimana', '초롱꽃과', '{6,7,8}', '6~8월', 'summer', '분홍', 'rare', '울릉도·화단', 'mid', '{144}', 3),
  (146, '잔대', 'Adenophora triphylla', '초롱꽃과', '{7,8,9}', '7~9월', 'summer', '보라', 'normal', '산지·풀밭', 'mid', '{}', 3),
  (147, '참나리', 'Lilium lancifolium', '백합과', '{7,8}', '7~8월', 'summer', '주황', 'normal', '산기슭·화단', 'low', '{148}', 1),
  (148, '백합', 'Lilium longiflorum', '백합과', '{6,7}', '6~7월', 'summer', '흰색', 'normal', '화단·화분', 'mid', '{147}', 2),
  (149, '원추리', 'Hemerocallis fulva', '백합과', '{6,7,8}', '6~8월', 'summer', '주황', 'common', '도로변·공원', 'mid', '{150,147}', 1),
  (150, '노랑원추리', 'Hemerocallis thunbergii', '백합과', '{7,8}', '7~8월', 'summer', '노랑', 'normal', '공원·화단', 'mid', '{149}', 2),
  (151, '옥잠화', 'Hosta plantaginea', '백합과', '{8,9}', '8~9월', 'autumn', '흰색', 'normal', '화단·공원', 'mid', '{152}', 2),
  (152, '비비추', 'Hosta longipes', '백합과', '{7,8}', '7~8월', 'summer', '보라', 'common', '화단·공원 그늘', 'mid', '{151}', 1),
  (153, '상사화', 'Lycoris squamigera', '수선화과', '{7,8}', '7~8월', 'summer', '분홍', 'normal', '공원·사찰', 'low', '{188}', 2),
  (154, '연꽃', 'Nelumbo nucifera', '연꽃과', '{7,8}', '7~8월', 'summer', '분홍', 'normal', '연못·수생공원', 'low', '{155}', 1),
  (155, '수련', 'Nymphaea tetragona', '수련과', '{6,7,8}', '6~8월', 'summer', '흰색', 'normal', '연못', 'low', '{154}', 2),
  (156, '부추꽃', 'Allium tuberosum', '백합과', '{8,9}', '8~9월', 'summer', '흰색', 'common', '밭·화단', 'mid', '{198}', 2),
  (157, '백일홍', 'Zinnia elegans', '국화과', '{6,7,8,9,10}', '6~10월', 'summer', '기타', 'common', '화단', 'mid', '{173}', 1),
  (158, '채송화', 'Portulaca grandiflora', '쇠비름과', '{6,7,8,9}', '6~9월', 'summer', '기타', 'common', '화단·화분', 'mid', '{159}', 1),
  (159, '송엽국', 'Lampranthus spectabilis', '석류풀과', '{4,5,6}', '4~6월', 'summer', '분홍', 'common', '화단·경사면', 'mid', '{158}', 1),
  (160, '페튜니아', 'Petunia hybrida', '가지과', '{5,6,7,8,9,10}', '5~10월', 'summer', '기타', 'common', '화단·걸이 화분', 'mid', '{}', 1),
  (161, '메리골드', 'Tagetes erecta', '국화과', '{6,7,8,9,10}', '6~10월', 'summer', '주황', 'common', '화단', 'mid', '{162}', 1),
  (162, '만수국', 'Tagetes patula', '국화과', '{6,7,8,9,10}', '6~10월', 'summer', '노랑', 'common', '화단', 'high', '{161}', 2),
  (163, '깨꽃', 'Salvia splendens', '꿀풀과', '{6,7,8,9,10}', '6~10월', 'summer', '붉은색', 'common', '화단', 'low', '{}', 1),
  (164, '맨드라미', 'Celosia cristata', '비름과', '{7,8,9}', '7~9월', 'summer', '붉은색', 'normal', '화단', 'low', '{}', 2),
  (165, '제라늄', 'Pelargonium inquinans', '쥐손이풀과', '{5,6,7,8,9,10}', '5~10월', 'summer', '붉은색', 'common', '화분·베란다', 'mid', '{}', 2),
  (166, '임파첸스', 'Impatiens walleriana', '봉선화과', '{6,7,8,9,10}', '6~10월', 'summer', '분홍', 'common', '화단 그늘', 'high', '{130,167}', 2),
  (167, '베고니아', 'Begonia semperflorens', '베고니아과', '{5,6,7,8,9,10}', '5~10월', 'summer', '분홍', 'common', '화단·화분', 'mid', '{166}', 2),
  (168, '버들마편초', 'Verbena bonariensis', '마편초과', '{7,8,9}', '7~9월', 'summer', '보라', 'common', '화단·경관 초지', 'mid', '{169}', 2),
  (169, '버베나', 'Verbena hybrida', '마편초과', '{5,6,7,8,9}', '5~9월', 'summer', '보라', 'normal', '화단·화분', 'mid', '{168}', 3),
  (170, '수레국화', 'Centaurea cyanus', '국화과', '{6,7}', '6~7월', 'summer', '파랑', 'normal', '화단·경관 초지', 'low', '{}', 2),
  (171, '안개꽃', 'Gypsophila elegans', '석죽과', '{6,7}', '6~7월', 'summer', '흰색', 'normal', '화단·꽃다발', 'mid', '{}', 3),
  (172, '가자니아', 'Gazania rigens', '국화과', '{6,7,8,9}', '6~9월', 'summer', '노랑', 'normal', '화단', 'mid', '{}', 3),
  (173, '다알리아', 'Dahlia pinnata', '국화과', '{7,8,9,10}', '7~10월', 'summer', '기타', 'normal', '화단', 'mid', '{157}', 2),
  (174, '글라디올러스', 'Gladiolus hybridus', '붓꽃과', '{7,8}', '7~8월', 'summer', '기타', 'normal', '화단·밭', 'mid', '{}', 3),
  (175, '칸나', 'Canna generalis', '홍초과', '{7,8,9}', '7~9월', 'summer', '붉은색', 'normal', '화단·공원', 'low', '{}', 2),
  (176, '한련화', 'Tropaeolum majus', '한련과', '{6,7,8,9}', '6~9월', 'summer', '주황', 'normal', '화단·화분', 'mid', '{}', 3),
  (177, '천일홍', 'Gomphrena globosa', '비름과', '{7,8,9,10}', '7~10월', 'summer', '분홍', 'normal', '화단', 'low', '{}', 2),
  (178, '아게라텀', 'Ageratum houstonianum', '국화과', '{6,7,8,9}', '6~9월', 'summer', '보라', 'normal', '화단', 'mid', '{}', 3),
  (179, '국화', 'Chrysanthemum morifolium', '국화과', '{10,11}', '10~11월', 'autumn', '기타', 'common', '화단·전시·화분', 'mid', '{180,181}', 1),
  (180, '산국', 'Chrysanthemum boreale', '국화과', '{9,10,11}', '9~11월', 'autumn', '노랑', 'normal', '산기슭·풀밭', 'high', '{181,179}', 2),
  (181, '감국', 'Chrysanthemum indicum', '국화과', '{10,11}', '10~11월', 'autumn', '노랑', 'normal', '산기슭·해안', 'high', '{180}', 3),
  (182, '구절초', 'Dendranthema zawadskii', '국화과', '{9,10}', '9~10월', 'autumn', '흰색', 'normal', '산지·화단', 'mid', '{184,183}', 1),
  (183, '벌개미취', 'Aster koraiensis', '국화과', '{6,7,8,9,10}', '6~10월', 'autumn', '보라', 'common', '도로변·공원', 'high', '{184,185}', 1),
  (184, '쑥부쟁이', 'Aster yomena', '국화과', '{8,9,10}', '8~10월', 'autumn', '보라', 'common', '길가·풀밭', 'high', '{183,186}', 1),
  (185, '개미취', 'Aster tataricus', '국화과', '{8,9,10}', '8~10월', 'autumn', '보라', 'normal', '산지·화단', 'high', '{183}', 2),
  (186, '미국쑥부쟁이', 'Symphyotrichum pilosum', '국화과', '{9,10}', '9~10월', 'autumn', '흰색', 'common', '공터·도로변', 'high', '{184,101}', 2),
  (187, '참취', 'Aster scaber', '국화과', '{8,9,10}', '8~10월', 'autumn', '흰색', 'normal', '산지 숲', 'high', '{186}', 3),
  (188, '꽃무릇', 'Lycoris radiata', '수선화과', '{9,10}', '9~10월', 'autumn', '붉은색', 'normal', '사찰·공원', 'low', '{153}', 1),
  (189, '용담', 'Gentiana scabra', '용담과', '{9,10}', '9~10월', 'autumn', '파랑', 'rare', '산지 풀밭', 'mid', '{}', 3),
  (190, '투구꽃', 'Aconitum jaluense', '미나리아재비과', '{9,10}', '9~10월', 'autumn', '보라', 'rare', '산지 숲', 'mid', '{}', 3),
  (191, '마타리', 'Patrinia scabiosifolia', '마타리과', '{8,9,10}', '8~10월', 'autumn', '노랑', 'normal', '산기슭·풀밭', 'mid', '{192}', 2),
  (192, '뚝갈', 'Patrinia villosa', '마타리과', '{8,9}', '8~9월', 'autumn', '흰색', 'normal', '산기슭', 'high', '{191}', 3),
  (193, '며느리밥풀꽃', 'Melampyrum roseum', '현삼과', '{8,9}', '8~9월', 'autumn', '분홍', 'normal', '산지 숲', 'mid', '{}', 3),
  (194, '왕고들빼기', 'Lactuca indica', '국화과', '{8,9,10}', '8~10월', 'autumn', '노랑', 'common', '공터·길가', 'mid', '{46}', 2),
  (195, '방가지똥', 'Sonchus oleraceus', '국화과', '{5,6,7,8,9,10}', '5~10월', 'autumn', '노랑', 'common', '길가·화단 틈', 'high', '{45}', 3),
  (196, '미국가막사리', 'Bidens frondosa', '국화과', '{8,9,10}', '8~10월', 'autumn', '노랑', 'common', '물가·공터', 'mid', '{}', 3),
  (197, '서양등골나물', 'Ageratina altissima', '국화과', '{9,10}', '9~10월', 'autumn', '흰색', 'common', '산기슭·도심 숲', 'mid', '{}', 2),
  (198, '산부추', 'Allium thunbergii', '백합과', '{9,10}', '9~10월', 'autumn', '보라', 'normal', '산지·바위', 'mid', '{156}', 3),
  (199, '억새', 'Miscanthus sinensis', '벼과', '{9,10}', '9~10월', 'autumn', '기타', 'common', '산지·하천·억새밭', 'mid', '{200}', 1),
  (200, '수크령', 'Pennisetum alopecuroides', '벼과', '{8,9,10}', '8~10월', 'autumn', '기타', 'common', '길가·도로변', 'mid', '{199}', 2)
on conflict (id) do update set
  name               = excluded.name,
  scientific_name    = excluded.scientific_name,
  family             = excluded.family,
  bloom_months       = excluded.bloom_months,
  bloom_label        = excluded.bloom_label,
  season             = excluded.season,
  color              = excluded.color,
  rarity             = excluded.rarity,
  habitat            = excluded.habitat,
  ai_difficulty      = excluded.ai_difficulty,
  similar_flower_ids = excluded.similar_flower_ids,
  illust_batch       = excluded.illust_batch;

-- 적재 검증. 200종보다 적으면 뭔가 빠진 것이다.
-- (더 많은 것은 실패가 아니다 — 뒤 파일이 이미 돌았을 수 있다.)
do $$
declare n int;
begin
  select count(*) into n from public.flowers;
  if n < 200 then
    raise exception '도감 종수가 %개다. 200종 이상이어야 한다', n;
  end if;
end $$;
